services:

  catalogue:
    image: sainathvelaga/craftista:catalogue-1.0.0
    ports:
      - "5000:5000"
  voting:
    image: sainathvelaga/craftista:voting-1.0.0
    ports:
      - "8080:8080"

  recommendation:
    image: sainathvelaga/craftista:recommendation-1.0.0
    ports:
      - "8081:8080"



  frontend:
    image: sainathvelaga/craftista:frontend-1.0.0
    ports:
      - "80:3000"